### ISSUE TITLE
Multiple selections?

### ISSUE THREAD

**Issue by jashsayani** [heatherbooker/react-world-map#10]
It would be nice to allow multiple selections. `selected` can be an array like: `['na', 'sa', 'eu']`

**Comment by heatherbooker** [comment]
I agree, that could be cool! If you want to implement it and open a PR, while keeping backwards compatibility (ie, users should be able to pass either a string or an array for `selected`), I would be happy to review :)

**Comment by jashsayani** [comment]
Sure I can take a stab at it.

**Comment by Victomas97** [comment]
Hii! Can I change class components by functional components?

**Comment by heatherbooker** [comment]
Hi @Victomas97 ! You mean as a separate PR? Sure, that would be ok, thought you might have some merge conflicts with jashsayani if you plan to do it while #14 is being worked on.

**Comment by heatherbooker** [comment]
Done thanks to @jashsayani ! In ffeb977 and 27d1267.
