### ISSUE TITLE
'selection' is broken

### ISSUE THREAD

**Issue by jashsayani** [heatherbooker/react-world-map#11]
`<WorldMap selected={'na'} />` does not select North America. I see "Demo" link in README has a selection but does not select anything initially as well.

**Comment by heatherbooker** [comment]
Hi @jashsayani , I see what you mean. [This](https://github.com/heatherbooker/react-world-map/commit/828a1bba221882a4b8295711fc1a2d954d012510#diff-0e51ddd0f40ee210f284459d9ade2f6c051c9c669b606fed149435d2f4135164L8) should fix the demo, and [this](https://github.com/heatherbooker/react-world-map/commit/34920f686d945ba282f4ae8f21102a7ba429a1f4#diff-0b5adbfe7b36e4ae2f479291e20152e33e940f7f265162d77f40f6bdb5da7405L22) should fix the actual problem. I will release them soon. Thanks for pointing it out!

**Comment by heatherbooker** [comment]
I just released 2.2.0, if you try it let me know if it works for you. You can also test stuff out now at [this codepen demo](https://codepen.io/hboo/pen/yLaZWdb).

**Comment by jashsayani** [comment]
Thanks!

**Comment by heatherbooker** [comment]
Feel free to re-open if the issue comes up again :)
