### ISSUE TITLE
Add guidelines for repository contributors

### ISSUE THREAD

**Issue by jashsayani** [heatherbooker/react-world-map#12]
Mostly:
1. How to run locally
2. Submitting guidelines (PR in a branch or Fork the repo, etc)

**Comment by heatherbooker** [comment]
Good idea, I will see what I come up with. In the meantime:
- fork the repo, you won't have permission to push to a branch directly
- use npm to install dependencies `npm i` and build it `npm run build` and then build the demo `npm run build-demo`
- view the demo oldschool style, by opening `docs/index.html` in your browser
