### ISSUE TITLE
Update React peer dependency

### ISSUE THREAD

**Issue by VWRoli** [heatherbooker/react-world-map#26]
I had an issue installing this package into a React 17 project because of a peer dependency issue.
We could widen the peer dependency list to include React 17. `^16.13.1 || ^17.0.0`

**Comment by heatherbooker** [comment]
2.4.0 is now released:
https://www.npmjs.com/package/react-world-map

Please let me know if that solves everything for you. Thanks for the contribution! :heart:

**Comment by fustroli** [comment]
Works perfectly, thank you!
