### ISSUE TITLE
Would it be interesting to do it per country?

### ISSUE THREAD

**Issue by dbrrt** [heatherbooker/react-world-map#3]
Not really an issue, but it would really be a nice alternative selector for countries picking.

**Comment by heatherbooker** [comment]
True! I'm surprised if nothing else exists out there to do this. If there is a large need maybe I can look into it - depends on the availability of an existing SVG country-separated map, which IIRC is easier to come across than a continent-separated one.

**Comment by bendunn135** [comment]
I'm looking at doing just that, and I can't see anything else out there after a quick look. Any chance you've made a start already or maybe found a decent SVG for countries?

**Comment by dbrrt** [comment]
I'd like to contribute to this feature as this would be really useful for some projects I'm involved in.

**Comment by heatherbooker** [comment]
I haven't started work on it or found anything relevant so it would be great if someone did work on it! :)

**Comment by heatherbooker** [comment]
I imagine something like https://github.com/zcreativelabs/react-simple-maps fulfills this need elegantly; please comment if you feel there is still a need for this library to add a per-country option!

**Comment by dbrrt** [comment]
That's perfect ! Thanks a lot !
