### ISSUE TITLE
Ability to select continent with country code

### ISSUE THREAD

**Issue by jashsayani** [heatherbooker/react-world-map#8]
It would be nice to be able to use "us" to select North America, or "br" to select South America, or "sg" to select Asia, and "au" to select Oceania. Needs map of countries to continent.

**Comment by jashsayani** [comment]
Here is a CSV of 2 digit ISO country code to 2 letter continent code (used by this library). 

[country-iso-processed.zip](https://github.com/heatherbooker/react-world-map/files/5794280/country-iso-processed.zip)

**Comment by heatherbooker** [comment]
That could be interesting, though possibly a bit outside of normal use cases I would think. I think you can apply that easily enough as a user, in your onSelect, something like:
```js
const [selected, onSelectContinent] = React.useState(null);
const countryToContinent = { us: 'na', br: 'sa', sg: 'as', au: 'oc', ... };
const onSelectCountry = (country) => onSelectContinent(countryToContinent[country]);
return <WorldMap selected={selected} />
```
Nice work bringing the CSV already though, I have to say I appreciate your involvement! :)

**Comment by jashsayani** [comment]
I ended up implementing it in my app, but can be added as a helper util function in this module later. I did:

```

const getContinents = (countries) => {
  const selection = new Set([]);

  countries.forEach((country) => {
    selection.add(CountryMap[country]);
  });

  return Array.from(selection);
};

```

In my app, I use:

`<WorldMap selected={getContinents(props.countries)} onSelect={() => {}} />`

But `countries` is an array and results in multiple continents, so it needs multiple selection first :)

(use case is: I own stocks in X regions)

**Comment by heatherbooker** [comment]
Awesome! I'm going to close this then, glad you have a plan :+1:
