### ISSUE TITLE
Disable click selection?

### ISSUE THREAD

**Issue by jashsayani** [heatherbooker/react-world-map#9]
I want to show a map with pre-selected continents (North America, Asia, etc) and not allow users to click around and toggle selections. I see the svg has `onClick` handlers that toggle selections. It would be nice to have a prop to disable user selection.

Perhaps:
`<WorldMap selected={ 'sa' }  disableInteraction={true} />`

Implementation:
```
class ControlledWorldMap extends React.Component<Props> {
  onMapClick = (area: Continent) => {
     if (this.props.disableInteraction) return;
     ....
  }

....
}
```

**Comment by heatherbooker** [comment]
Hi @jashsayani ! You can control it yourself, by passing an `onSelect` function that checks in your own component. Something like
```jsx
YourComponent {
  state = { disableInteraction: true, selected: 'sa' }
  onSelect = (area) => {
    if (state.disableInteraction) { return; }
    setState({ selected: area });
  }
  return <WorldMap selected={ state.selected } onSelect={ onSelect } />;
}
```
This way, the early return statement will be triggered if you don't want interaction. Enjoy!

**Comment by jashsayani** [comment]
It does not use the onSelect provided. I tried `<WorldMap selected={'na'} onSelect={() => {}} />` but it does not use my NoOp.

**Comment by heatherbooker** [comment]
I'll look into it!

**Comment by heatherbooker** [comment]
Can you try 2.2.0 that I just released, and see if that fixes things?

**Comment by jashsayani** [comment]
Verified with `2.2.0`, the fix works. Thanks.
